# Generated by Django 3.1.4 on 2020-12-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
